// Curated silent-failure scenarios. Each has a success-shaped tool result, a contract,
// and two simulated worlds: `ok` (the tool really did it) and `bug` (silent failure).
export const SCENARIOS = [
  {
    id: "create_file", label: "create_file", tool: "create_file", category: "filesystem",
    blurb: "Writes a file — but did the file actually land?",
    call: { tool: "create_file", args: { path: "/notes/out.txt", contents: "hello world" }, result: { status: "success", path: "/notes/out.txt" } },
    contract: { tool: "create_file", description: "a non-empty file exists at the requested path",
      post: { check: "file_exists", path: "{{args.path}}", minSize: 1 } },
    worlds: { ok: { files: { "/notes/out.txt": { size: 11, content: "hello world" } } }, bug: { files: {} } },
    remediation: "retry create_file and confirm the write actually flushed to disk",
  },
  {
    id: "append_log", label: "append_log", tool: "append_log", category: "filesystem",
    blurb: "Appends a line to a log — is the line really there?",
    call: { tool: "append_log", args: { path: "/var/app.log", line: "ORDER 42 shipped" }, result: { status: "ok" } },
    contract: { tool: "append_log", description: "the log contains the appended line",
      post: { check: "file_exists", path: "{{args.path}}", contains: "ORDER 42 shipped" } },
    worlds: { ok: { files: { "/var/app.log": { size: 64, content: "...\nORDER 42 shipped\n" } } },
      bug: { files: { "/var/app.log": { size: 40, content: "...older lines...\n" } } } },
    remediation: "the write opened the file but the line was never flushed — fsync and re-read",
  },
  {
    id: "save_record", label: "save_record", tool: "save_record", category: "db",
    blurb: "Persists a record to a store — or only claims to.",
    call: { tool: "save_record", args: { id: "r1", body: "buy milk" }, result: { status: "success", id: "r1" } },
    contract: { tool: "save_record", description: "the record is persisted in the store",
      post: { verify: (ctx, world) => !!(world.store && world.store[ctx.args.id]), describe: "record persisted in the store" } },
    worlds: { ok: { store: { r1: { id: "r1", body: "buy milk" } } }, bug: { store: {} } },
    remediation: "the write returned success but committed nothing — retry inside a transaction and verify the row",
  },
  {
    id: "charge_card", label: "charge_card", tool: "charge_card", category: "db",
    blurb: "Charges a card — did the payment actually post?",
    call: { tool: "charge_card", args: { id: "pay_9", amount: 4200 }, result: { status: "success", id: "pay_9" } },
    contract: { tool: "charge_card", description: "the payment is marked paid",
      post: { verify: (ctx, world) => ((world.payments && world.payments[ctx.args.id]) || {}).state === "paid", describe: "payment state is 'paid'" } },
    worlds: { ok: { payments: { pay_9: { state: "paid", amount: 4200 } } }, bug: { payments: { pay_9: { state: "pending", amount: 4200 } } } },
    remediation: "the gateway returned success but the charge is still pending — reconcile against the gateway before continuing",
  },
  {
    id: "send_email", label: "send_email", tool: "send_email", category: "api",
    blurb: "Sends an email — re-fetch to confirm it really sent.",
    call: { tool: "send_email", args: { to: "a@b.com", id: "m1" }, result: { status: "success", id: "m1" } },
    contract: { tool: "send_email", description: "a sent message exists for this recipient",
      post: { check: "http", url: "https://mail.local/api/messages/{{result.id}}", status: 200, jsonPath: "state", equals: "sent" } },
    worlds: { ok: { http: { "https://mail.local/api/messages/m1": { status: 200, body: { state: "sent" } } } },
      bug: { http: { "https://mail.local/api/messages/m1": { status: 404, body: {} } } } },
    remediation: "the API returned 200 but no message record exists — re-queue the send and re-check",
  },
  {
    id: "deploy_build", label: "deploy_build", tool: "deploy_build", category: "shell",
    blurb: "Runs a deploy script — did it exit clean AND mark done?",
    call: { tool: "deploy_build", args: { env: "prod" }, result: { status: "success", marker: "dist/BUILT" } },
    contract: { tool: "deploy_build", description: "deploy exited 0 and reported a marker",
      post: [ { check: "shell", cmd: "test -f dist/BUILT", exitCode: 0 }, { check: "result", path: "marker", exists: true } ] },
    worlds: { ok: { shell: { "test -f dist/BUILT": { exitCode: 0, stdout: "" } } },
      bug: { shell: { "test -f dist/BUILT": { exitCode: 1, stdout: "" } } } },
    remediation: "the deploy reported success but the build marker is missing — the artifact never published; re-run and gate on the marker",
  },
  {
    id: "publish_post", label: "publish_post", tool: "publish_post", category: "composite",
    blurb: "Publishes a post — result looks right AND the URL resolves?",
    call: { tool: "publish_post", args: { slug: "hello" }, result: { status: "success", url: "https://blog.local/p/hello" } },
    contract: { tool: "publish_post", description: "the result has a url and that url is live",
      post: [ { check: "result", path: "url", exists: true }, { check: "http", url: "{{result.url}}", status: 200 } ] },
    worlds: { ok: { http: { "https://blog.local/p/hello": { status: 200, body: {} } } },
      bug: { http: { "https://blog.local/p/hello": { status: 404, body: {} } } } },
    remediation: "the publish call returned a URL that 404s — the post row exists but wasn't rendered; trigger a rebuild and re-check the URL",
  },
];
